import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Nav from "../components/Nav";
import Provider from "@./context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="main">
            <div className="gradient" />
          </div>
          <Provider>
            <main className="app">
              <Nav />
              {children}
            </main>
          </Provider>
        </div>
      </body>
    </html>
  );
}
